const mongoose = require('mongoose');

const aspiranteSchema = mongoose.Schema({
  nombre: { type: String, required: true },
  apellidos: { type: String, required: true },
  alias: { type: String },
  ci: { type: String, required: true },
  edad: { type: String, required: true },
  sexo: { type: String, required: true },
  provincia: { type: String, required: true },
  municipio: { type: String, required: true },
  direccion: { type: String, required: true },
  correo: { type: String, required: true },
  telefono: { type: String },
  raza: { type: String, required: true },
  estatura: { type: String, required: true },
  peso: { type: String, required: true },
  estado_civil: { type: String, required: true },
  hijos: { type: String },
  licencia: { type: Boolean, required: true },
  categoria_licencia: { type: String },
  militancia: { type: String },
  nivel_escolaridad: { type: String, required: true },
  titulo_graduado: { type: String, required: true },
  experiencia_laboral: { type: String, required: true },
  otros_estudios: { type: String },
  trayectoria_laboral: { type: Array },
  situacion_laboral: { type: String, required: true },
  centro_trabajo: { type: String },
  organismo_trabajo: { type: String },
  cargo_trabajo: { type: String },
  categoria_trabajo: { type: String },
  direccion_trabajo: { type: String },
  telefono_trabajo: { type: String },
  otros_oficios: { type: String },
  estado: { type: String },
  causa_eliminacion: { type: String },
  causa_no_apto: { type: String },
  preseleccion: { type: String },
  fecha_inicio_proceso_investigativo: { type: String },
  fecha_fin_proceso_investigativo: { type: String },
  resultado_proceso_investigativo: { type: String },
  curriculum_vitae: { type: Boolean },
  fecha_curriculum_vitae: { type: String },
  autobiografia: { type: Boolean },
  fecha_autobiografia: { type: String },
  titulo: { type: Boolean },
  fecha_titulo: { type: String },
  chequeo_medico: { type: Boolean },
  fecha_chequeo_medico: { type: String },
  avales_cdr: { type: Boolean },
  fecha_avales_cdr: { type: String },
  avales_centro_trabajo: { type: Boolean },
  fecha_avales_centro_trabajo: { type: String },
  fotos: { type: Boolean },
  fecha_fotos: { type: String },
  anexo1: { type: Boolean },
  fecha_anexo1: { type: String },
  antecedentes: { type: Boolean },
  fecha_antecedentes: { type: String },
  evaluacion_psicologica: { type: String },
  comite_admision: { type: String },
  mixta: { type: String },
  cargo_mixta: { type: String },
  fecha_mixta: { type: String },
  causa_devolucion: { type: String },
  fecha_devolucion: { type: String },
});

module.exports = mongoose.model('Aspirante', aspiranteSchema);
